# Site settings
author: Joshua Sanders 
title: Out of the comfort zone. 
header-img: img/home-bg.png
email: ninjosh2@gmail.com
copyright_name: Joshua Sanders 
description: > # this means to ignore newlines until "baseurl:"
  Or : Why did I decided to peruse software development?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ninjosh2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
